name = "UnregisteredB"
uuid = "4a15487d-6a03-40fd-be4e-f31ac6f07bdf"
authors = ["David Varela <00.varela.david@gmail.com>"]
version = "0.1.0"

[deps]
UnregisteredC = "576bedce-fdcc-4209-9e0a-2d2da9eed307"

[source]
UnregisteredC = "https://github.com/00vareladavid/UnregisteredC"
